version: '3.5'
services:
  postgres_db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://127.0.0.1:9092
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    ports:
      - 9092:9092
    expose:
      - 9093
    volumes:
      - /tmp/kafka/:/etc/kafka
    depends_on:
      - zookeeper

  test-task-rbkmoney:
    image: epoddubnyi/test-task-rbkmoney:0.0.1
    restart: always
    mem_limit: 800m
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseStringDeduplication -Xss256k -XX:MaxRAMPercentage=70.0 -XX:InitialRAMPercentage=70.0
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgres_db
      - kafka


