version: '3.5'
services:
  postgres_db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data

  test-task-rbkmoney:
    image: epoddubnyi/test-task-rbkmoney:0.0.1
    restart: always
    mem_limit: 800m
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseStringDeduplication -Xss256k -XX:MaxRAMPercentage=70.0 -XX:InitialRAMPercentage=70.0
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgres_db


