server:
  port: ${PORT:11213}

spring:
  application:
    name: @project.name@
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}?ApplicationName=${spring.application.name}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    ROOT: INFO
    com.github.epoddubny.testtaskrbkmoney: ERROR