spring:
  server:
    port: ${PORT:11213}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    hikari:
      connection-timeout: 3000
      idle-timeout: 10000
      max-lifetime: 60000

logging:
  level:
    ROOT: ERROR
    com.github.epoddubny.testtaskrbkmoney: ERROR